#!/bin/sh

undofiles_path="${HOME}/.vim/undofiles"

print_usage() {
    cat <<- EOF
    $(basename $0) [-u <undodir>] [-p] [-h]

    This script removes vim undo files that do not have a correspdoning file
    anymore.  The undo files must be stored centrally in one "undodir".

    Options:
     -u           The path to "undodir" (without a trailing slash; default:
                  ${undofiles_path}).
     -p           Only display what would be done (pretend).
     -h           Display this help text.
EOF
    exit
}

while getopts u:ph a;
do
    case $a in
        u) undofiles_path="$OPTARG";;
        p) pretend=1;;
        h) print_usage;;
        *) echo "\nUsage:\n"
            print_usage;;
    esac
done
shift $(expr $OPTIND - 1)

# I have a keep file in undodir so that git keeps the directory, since vim
# doesn't automatically create the directory.
keep_file="${undofiles_path}/.keep"

if [ -n "${pretend}" ]
then
    echo "I would do the following:"
fi

find "${undofiles_path}" -type f | while read undo_file
do
    edited_file="$(echo ${undo_file} | sed s:^./::)"
    edited_file="$(echo ${edited_file} | sed s:%:/:g)"
    edited_file="$(echo ${edited_file} | sed s:"${undofiles_path}/"::)"

    if [ ! -e "${edited_file}" -a "${undo_file}" != "${keep_file}" ]
    then
        echo "Removing obsolete undo file \"${undo_file}\""
        if [ -z "${pretend}" ]
        then
            rm "${undo_file}"
        fi
    fi
done
